# This CI script uses a pre-build `kernel-builder` container on coldroom.tpl
# This container is based on debian:buster and have all the necessary packages
# installed, as well as applied patch for kernel-package to install device
# blob tree file in /boot instead of standard path defined by kernel.
image: "kernel-builder"

variables:
  GIT_SSL_NO_VERIFY: "1"                     # Allow self-signed certificates (REQUIRED for gitlab.tpl)
  ARCH:              "mips"                  # Build kernel for the specified arch
  EXTARCH:           "mipsel"                # Extended arch definition
  CC:                "mipsel-linux-gnu-gcc"  # CC variable
  DEB_HOST_ARCH:     "mipsel"
  CROSS_COMPILE:     "mipsel-linux-gnu-"     # Toolchain prefix
  SUFFIX:            "-extended"             # LOCALVERSION for the kernel
  DEFAULTCONF:       "tplatforms_mitx_ext_defconfig" # Use the specified defconfig file
  NJOBS:             "20"                    # Number of parralel build jobs

# Declaring REVISIONSTRING in variables section above is difficult due to 
# GitLab's way of parsing values: bash expansions won't work as expected.
before_script:
  - export REVISIONSTRING="$(date +%Y%m%d).$(git rev-parse --short HEAD)"

# This target builds debian packages for kernel image, source and headers
# using the defconfig passed in `DEFAULTCONF` variable.
# For minimal set of modules use `baikal_mitx_defconfig`
# For extended set of modules use `baikal_mitx_ext_defconfig`

build:
  script:
    # clean parent directory (in case previous job failed)
    - rm -f ../*.deb
    - ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE fakeroot make-kpkg --arch=$EXTARCH --cross-compile=$CROSS_COMPILE clean
    - ARCH=$ARCH make defconfig KBUILD_DEFCONFIG=$DEFAULTCONF
    - ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE LOCALVERSION=$SUFFIX fakeroot make-kpkg -j$NJOBS --arch=$EXTARCH --cross-compile=$CROSS_COMPILE --revision=$REVISIONSTRING kernel_image kernel_headers kernel_source
    # Gitlab can get artifacts only from inside the repo tree, but kernel
    # package puts them to parent directory. So we explicitly move them.
    - cp ../*deb ./
  artifacts:
    paths:
    - ./*.deb
    expire_in: 1 month
