image: $CI_REGISTRY/baikal-m/spi_builder:1.1

stages:
  - build

variables:
  GIT_DEPTH: 200

.build_kernel_template: &build_kernel_dfn
  stage: build
  script:
    - rm -f ../linux-*
    - make ARCH=mips CROSS_COMPILE=/usr/bin/mipsel-linux-gnu- ${DEFCONFIG}
    - make ARCH=mips CROSS_COMPILE=/usr/bin/mipsel-linux-gnu- ${DTBTARGET}
    - make ARCH=mips CROSS_COMPILE=/usr/bin/mipsel-linux-gnu- bindeb-pkg -j $(nproc)
    - |
      BRANCH=""
      if [ "$CI_COMMIT_BRANCH" != "$CI_DEFAULT_BRANCH" ]; then
        if [ -n "${CI_COMMIT_BRANCH}" ]; then
          BRANCH="${CI_COMMIT_BRANCH}"
        fi
      fi
      VERSION=$(git describe --tags)
      echo "Uploading version ${VERSION}"
      echo "          branch ${BRANCH}"
      echo "          board ${BOARD}"
      GIT_TAG=$(git describe --tags --no-abbrev)
      FULL_PATH="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/kernel/${GIT_TAG}/linux-${BOARD}-${BRANCH}-${VERSION}.tar"
      echo "Full path: ${FULL_PATH}"
      tar cf - --exclude='*-dbg_*' ../linux-*mipsel.deb | curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file - ${FULL_PATH}
    - rm -f ../linux-*

mitx:
  variables:
    DEFCONFIG: tplatforms_mitx_defconfig
    DTBTARGET: baikal/tplatforms_mitx.dtb 
    BOARD: "mitx"
  <<: *build_kernel_dfn

mitx-extra:
  variables:
    DEFCONFIG: tplatforms_mitx_ext_defconfig
    DTBTARGET: baikal/tplatforms_mitx.dtb 
    BOARD: "mitx-extra"
  <<: *build_kernel_dfn

et402-smarc:
  variables:
    DEFCONFIG: elpitech_et402_defconfig
    DTBTARGET: baikal/elpitech_et402.dtb
    BOARD: "et402"
  <<: *build_kernel_dfn

et412-brp:
  variables:
    DEFCONFIG: elpitech_et412_defconfig
    DTBTARGET: baikal/elpitech_et412.dtb
    BOARD: "et412"
  <<: *build_kernel_dfn
